### ISSUE TITLE
Failed to read .vcf and/ or copycat file

### ISSUE THREAD

**Issue by BCArg** [MariaNattestad/SplitThreader#4]
I have been using splitthread a few months back to analyse genomic variants seamlessly, though today I have been experiencing issues loading the files. 

I am using a snakemake pipeline from [https://github.com/nanoporetech/pipeline-structural-variation](nanopore) to call SVs on ONT data. This pipeline uses sniffles to generate the VCF and I am also using copycat to generate the copy number profile file.

After uplading the `vcf` and the copycat file I am getting the following message

```
Starting...

1. Reading input files

NOTE: Contains 'VCF' in a header row (starting with #), so treating it like a VCF file.

VCF file

WARNING: strand2 not matching between ALT bracket notation and STRANDS tag in INFO field. STRANDS tag takes precedent

STRANDS tag: ['--'] vs ALT text: ]chr3:197899578]N 
...
```

I don't recall receiving these warning messages in the past. The only thing that changed from when I was analysing the data without problems and now is that, back then I had the `vcf` and copycat file locally on my computer (I am running splitthreader locally, by the way). Now I need to `ssh -X` into a computer with GUI, where the drivers where `vcf`and copycat files are accessible. I don't see how it can be related to the installation, as splitthreader pops-up when I paste `localhost/splitthreader` on firefox.

`vcf` and copy number profile look normal. Would you like me to upload these files so that you can have a closer look?

Thanks in advance

**Comment by MariaNattestad** [comment]
This is a warning that the VCF format has two different ways to show the strand and that those are disagreeing with each other. It has nothing to do with where you are running SplitThreader; it's only about the VCF file format.
The presence of "]" in the ALT should mean that the strand is "+" but here it says it's "-". If you are concerned about the warning, please check with the Sniffles folks what that combination of ALT and STRANDS is supposed to mean, since it never appeared in previous VCF outputs from Sniffles (which I referred to while building this VCF reader for SplitThreader).

**Comment by BCArg** [comment]
Actually it was just a warning and the 'show visulizer' button did not show up, probably because I was using the GUI from a remote server with `ssh -X`, which was terribly slow. It works fine when I am using split threader on my local installation
