### ISSUE TITLE
small chromosomes missing

### ISSUE THREAD

**Issue by vmukhina** [MariaNattestad/SplitThreader#6]
Hi Maria,
viral chromosomes and chrM are filtered out on splitthreader figures (and human-viral BND's too). Do you know if there is an easy way to fix this? What is the minimal chr size that will work?
Thank you,
Vera

**Comment by MariaNattestad** [comment]
Hi Vera

They're filtered out to make the visualization look reasonable, since they would be tiny slivers in the circos plot. The relevant code is here:
https://github.com/MariaNattestad/SplitThreader/blob/76a1206626280ab0a2ecec5e88ca8f58f8609fca/js/SplitThreader_visualizer.js#L575C4-L576C1
and the comment says "only include chromosomes accounting for at least 1% of the total genome sequence".
As a workaround, you could try running SplitThreader where you exclude the larger chromosomes from your data, especially from the copy number input file, which is used to determine the sizes of the chromosomes.

Maria

**Comment by vmukhina** [comment]
Thank you Maria! I've changed the script according to your recommendations: now we have small chromosomes in circle plot but their representation on the right panel glitches and I can't drag the chromosome there. This is probably related to the low copy-number file resolution (my virus is about 10kb). I also failed to use 
To zoom in I used mosdepth instead of copycat to create coverage files with 3kb resolution in bed format. It needs header and tab to comma separator replacement, but works overall much faster and you can choose any the resolution. 
Online splitthreader version works with 3kb resolution but I failed to run it locally. Thats pity because your visualisation tool looks very useful for complex rearrangements like mine.

PS2 it's probably worth to mention in the readme that SplitThreader needs an old python version 2.7.

**Comment by MariaNattestad** [comment]
You might have more luck with my other tool Ribbon then which is more about
zooming in on actual reads in detail, try genomeribbon.com

**Comment by vmukhina** [comment]
Thank you! Ribbon was my starting point. It's nice, but I prefer the splitthreader representation.
